room25
* class Rule to handle specific game config such as:
** Board init
** win/lose condition
** turn handling (cpt, rotation of player)
** action available

* resolve effect of room:
** freezeroom -> Scheduling should have only one action
** vortexroom -> avatar send on center room
** wormroom -> avatar should go to another visible wormroom
** visionroom -> select a room and apply see on it (change Board::see to be able to take a Cell directly)
** gearroom -> select a cell (except center) and apply a valid slide on it (change Board::slide to be able to take a Cell directly)
** illusionroom -> give a list of coordinate to player that should return the index in the vector of the one he want to see, then if valid switch roomeffect and activate the one of the room taken
** warproom -> give a list of coordinate to player that should return the index in the vector of the one he want to see, then if valid  switch the room inside the two cell

* Scheduling/Game handle mono action (first or second sequence) (DONE)
* Guardian programmation (no scheduling for guardian?)
* add static Sheduling::validate(scheduling, Avatar) (DONE without avatar)

* In Game::execPush only append valid target (not myself and not Robot) /* maybe in Rule? */
* truly handle turn (dead people does not play anymore)


* NetworkPlayer
Il n'aura pas toutes les infos bien claires mais il pourra envoyer au game.
Quitte a ce qu'il ait un main degueu.

- Refaire la communication network de base
- NetworkHostPlayer
- NetworkClientPlayer
- Le main en mode on s'emmerde pas

Pas trop s'emmerder avec le display des infos. On fait ce qui est necessaire
(alias demander les actions que le joueur veut faire).
* PlaybackPlayer
Se connecte au network et de la même manière que le main degueu, il rejoue une
action qu'on lui dit.

- Interroge le reseau quand on lui demande son scheduling, ...
- Nouveau main d'envoi d'actions vers lui
* GameClient
Juste un NetworkPlayer et des PlaybackPlayer.

- Modifier le game server pour qu'il broadcast les infos recues d'un network
  player.
- pas clair a voir
